# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1241, 842)
        Dialog.setWindowTitle("Make trainData for diffLayer lineDetector")
        self.view = QtWidgets.QGraphicsView(Dialog)
        self.view.setGeometry(QtCore.QRect(10, 10, 204, 204))
        self.view.setObjectName("view")
        self.viewLarge = QtWidgets.QGraphicsView(Dialog)
        self.viewLarge.setGeometry(QtCore.QRect(428, 10, 804, 804))
        self.viewLarge.setObjectName("viewLarge")
        self.view1 = QtWidgets.QGraphicsView(Dialog)
        self.view1.setGeometry(QtCore.QRect(218, 10, 204, 204))
        self.view1.setObjectName("view1")
        self.btnSave = QtWidgets.QPushButton(Dialog)
        self.btnSave.setGeometry(QtCore.QRect(180, 630, 51, 23))
        self.btnSave.setObjectName("btnSave")
        self.leTrainFileName = QtWidgets.QLineEdit(Dialog)
        self.leTrainFileName.setGeometry(QtCore.QRect(240, 630, 51, 21))
        self.leTrainFileName.setObjectName("leTrainFileName")
        self.sboxTrainFileName = QtWidgets.QSpinBox(Dialog)
        self.sboxTrainFileName.setGeometry(QtCore.QRect(290, 630, 51, 21))
        self.sboxTrainFileName.setMaximum(9999)
        self.sboxTrainFileName.setObjectName("sboxTrainFileName")
        self.btnLoad = QtWidgets.QPushButton(Dialog)
        self.btnLoad.setGeometry(QtCore.QRect(350, 630, 51, 23))
        self.btnLoad.setObjectName("btnLoad")
        self.view2 = QtWidgets.QGraphicsView(Dialog)
        self.view2.setGeometry(QtCore.QRect(12, 218, 404, 404))
        self.view2.setObjectName("view2")
        self.btnBatchCalcLabel = QtWidgets.QPushButton(Dialog)
        self.btnBatchCalcLabel.setGeometry(QtCore.QRect(182, 660, 91, 31))
        self.btnBatchCalcLabel.setObjectName("btnBatchCalcLabel")
        self.btnTraining = QtWidgets.QPushButton(Dialog)
        self.btnTraining.setGeometry(QtCore.QRect(182, 740, 141, 31))
        self.btnTraining.setObjectName("btnTraining")
        self.chBoxDrawPredict = QtWidgets.QCheckBox(Dialog)
        self.chBoxDrawPredict.setGeometry(QtCore.QRect(100, 750, 81, 16))
        self.chBoxDrawPredict.setObjectName("chBoxDrawPredict")
        self.btnPatch = QtWidgets.QPushButton(Dialog)
        self.btnPatch.setGeometry(QtCore.QRect(352, 660, 61, 31))
        self.btnPatch.setObjectName("btnPatch")
        self.btnClear = QtWidgets.QPushButton(Dialog)
        self.btnClear.setGeometry(QtCore.QRect(10, 700, 75, 31))
        self.btnClear.setObjectName("btnClear")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 630, 158, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.btnCircle = QtWidgets.QPushButton(self.layoutWidget)
        self.btnCircle.setObjectName("btnCircle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.btnCircle)
        self.btnLine = QtWidgets.QPushButton(self.layoutWidget)
        self.btnLine.setObjectName("btnLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btnLine)
        self.btnRandDraw = QtWidgets.QPushButton(self.layoutWidget)
        self.btnRandDraw.setObjectName("btnRandDraw")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.btnRandDraw)
        self.btnCalcTrainLabel = QtWidgets.QPushButton(self.layoutWidget)
        self.btnCalcTrainLabel.setObjectName("btnCalcTrainLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.btnCalcTrainLabel)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(182, 700, 231, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.edPath = QtWidgets.QLineEdit(self.layoutWidget1)
        self.edPath.setObjectName("edPath")
        self.horizontalLayout.addWidget(self.edPath)
        self.btnMergeData = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnMergeData.setObjectName("btnMergeData")
        self.horizontalLayout.addWidget(self.btnMergeData)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(332, 741, 73, 31))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboClassNo = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboClassNo.setMaxCount(2)
        self.comboClassNo.setObjectName("comboClassNo")
        self.comboClassNo.addItem("")
        self.comboClassNo.addItem("")
        self.horizontalLayout_2.addWidget(self.comboClassNo)
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboGrey = QtWidgets.QComboBox(Dialog)
        self.comboGrey.setGeometry(QtCore.QRect(280, 660, 61, 31))
        self.comboGrey.setObjectName("comboGrey")
        self.comboGrey.addItem("")
        self.comboGrey.addItem("")
        self.btnGetParameters = QtWidgets.QPushButton(Dialog)
        self.btnGetParameters.setGeometry(QtCore.QRect(180, 780, 91, 31))
        self.btnGetParameters.setObjectName("btnGetParameters")
        self.btnPredict = QtWidgets.QPushButton(Dialog)
        self.btnPredict.setGeometry(QtCore.QRect(280, 780, 91, 31))
        self.btnPredict.setObjectName("btnPredict")
        self.btnClearParameters = QtWidgets.QPushButton(Dialog)
        self.btnClearParameters.setGeometry(QtCore.QRect(80, 780, 91, 31))
        self.btnClearParameters.setObjectName("btnClearParameters")
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.view.raise_()
        self.viewLarge.raise_()
        self.view1.raise_()
        self.btnSave.raise_()
        self.leTrainFileName.raise_()
        self.sboxTrainFileName.raise_()
        self.btnLoad.raise_()
        self.view2.raise_()
        self.btnBatchCalcLabel.raise_()
        self.btnTraining.raise_()
        self.chBoxDrawPredict.raise_()
        self.btnPatch.raise_()
        self.btnClear.raise_()
        self.comboGrey.raise_()
        self.btnGetParameters.raise_()
        self.btnPredict.raise_()
        self.btnClearParameters.raise_()

        self.retranslateUi(Dialog)
        self.btnSave.clicked.connect(Dialog.doSaveData)
        self.btnLoad.clicked.connect(Dialog.doLoadData)
        self.btnBatchCalcLabel.clicked.connect(Dialog.doBatchCalcLabel)
        self.btnTraining.clicked.connect(Dialog.doTraining)
        self.btnMergeData.clicked.connect(Dialog.doMergeData)
        self.btnPatch.clicked.connect(Dialog.doPatch)
        self.btnClear.clicked.connect(Dialog.clearWorld)
        self.btnCalcTrainLabel.clicked.connect(Dialog.calcTrainLabel)
        self.btnRandDraw.clicked.connect(Dialog.doRandDraw)
        self.btnLine.clicked.connect(Dialog.doLine)
        self.btnCircle.clicked.connect(Dialog.doCircle)
        self.btnGetParameters.clicked.connect(Dialog.doGetParameters)
        self.btnPredict.clicked.connect(Dialog.doPredict)
        self.btnClearParameters.clicked.connect(Dialog.doClearParameters)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.btnLine, self.view)
        Dialog.setTabOrder(self.view, self.viewLarge)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.btnSave.setText(_translate("Dialog", "Save"))
        self.leTrainFileName.setText(_translate("Dialog", "BA/BA"))
        self.btnLoad.setText(_translate("Dialog", "Load"))
        self.btnBatchCalcLabel.setText(_translate("Dialog", "BatchCalcLabel"))
        self.btnTraining.setText(_translate("Dialog", "Training"))
        self.chBoxDrawPredict.setText(_translate("Dialog", "DrawPredict"))
        self.btnPatch.setText(_translate("Dialog", "Patch"))
        self.btnClear.setText(_translate("Dialog", "Clear"))
        self.btnCircle.setText(_translate("Dialog", "DrawCircle"))
        self.btnLine.setText(_translate("Dialog", "DrawLine"))
        self.btnRandDraw.setText(_translate("Dialog", "RandDraw"))
        self.btnCalcTrainLabel.setText(_translate("Dialog", "CalcLabel"))
        self.label_2.setText(_translate("Dialog", "Batch on"))
        self.edPath.setText(_translate("Dialog", "E"))
        self.btnMergeData.setText(_translate("Dialog", "MergeData"))
        self.comboClassNo.setItemText(0, _translate("Dialog", "2"))
        self.comboClassNo.setItemText(1, _translate("Dialog", "5"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>Classes</p></body></html>"))
        self.comboGrey.setItemText(0, _translate("Dialog", "Grey"))
        self.comboGrey.setItemText(1, _translate("Dialog", "Mono"))
        self.btnGetParameters.setText(_translate("Dialog", "GetParameters"))
        self.btnPredict.setText(_translate("Dialog", "Predict"))
        self.btnClearParameters.setText(_translate("Dialog", "ClearParameters"))


