# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1241, 842)
        Dialog.setWindowTitle("Make trainData for diffLayer lineDetector")
        self.view = QtWidgets.QGraphicsView(Dialog)
        self.view.setGeometry(QtCore.QRect(10, 10, 204, 204))
        self.view.setObjectName("view")
        self.viewLarge = QtWidgets.QGraphicsView(Dialog)
        self.viewLarge.setGeometry(QtCore.QRect(428, 10, 804, 804))
        self.viewLarge.setObjectName("viewLarge")
        self.view1 = QtWidgets.QGraphicsView(Dialog)
        self.view1.setGeometry(QtCore.QRect(218, 10, 204, 204))
        self.view1.setObjectName("view1")
        self.btnSave = QtWidgets.QPushButton(Dialog)
        self.btnSave.setGeometry(QtCore.QRect(150, 630, 51, 23))
        self.btnSave.setObjectName("btnSave")
        self.leTrainFileName = QtWidgets.QLineEdit(Dialog)
        self.leTrainFileName.setGeometry(QtCore.QRect(210, 630, 51, 21))
        self.leTrainFileName.setObjectName("leTrainFileName")
        self.sboxTrainFileName = QtWidgets.QSpinBox(Dialog)
        self.sboxTrainFileName.setGeometry(QtCore.QRect(260, 630, 51, 21))
        self.sboxTrainFileName.setMaximum(9999)
        self.sboxTrainFileName.setObjectName("sboxTrainFileName")
        self.btnLoad = QtWidgets.QPushButton(Dialog)
        self.btnLoad.setGeometry(QtCore.QRect(320, 630, 61, 23))
        self.btnLoad.setObjectName("btnLoad")
        self.view2 = QtWidgets.QGraphicsView(Dialog)
        self.view2.setGeometry(QtCore.QRect(12, 218, 404, 404))
        self.view2.setObjectName("view2")
        self.btnBatchGenerateLabel = QtWidgets.QPushButton(Dialog)
        self.btnBatchGenerateLabel.setGeometry(QtCore.QRect(150, 670, 111, 31))
        self.btnBatchGenerateLabel.setObjectName("btnBatchGenerateLabel")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(150, 710, 61, 16))
        self.label_2.setObjectName("label_2")
        self.edPath = QtWidgets.QLineEdit(Dialog)
        self.edPath.setGeometry(QtCore.QRect(220, 710, 71, 20))
        self.edPath.setObjectName("edPath")
        self.btnTraining = QtWidgets.QPushButton(Dialog)
        self.btnTraining.setGeometry(QtCore.QRect(150, 740, 141, 31))
        self.btnTraining.setObjectName("btnTraining")
        self.btnMergeData = QtWidgets.QPushButton(Dialog)
        self.btnMergeData.setGeometry(QtCore.QRect(300, 700, 75, 31))
        self.btnMergeData.setObjectName("btnMergeData")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(40, 630, 81, 151))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.btnCircle = QtWidgets.QPushButton(self.splitter)
        self.btnCircle.setObjectName("btnCircle")
        self.btnLine = QtWidgets.QPushButton(self.splitter)
        self.btnLine.setObjectName("btnLine")
        self.btnRandDraw = QtWidgets.QPushButton(self.splitter)
        self.btnRandDraw.setObjectName("btnRandDraw")
        self.btnCalcTrainLabel = QtWidgets.QPushButton(self.splitter)
        self.btnCalcTrainLabel.setObjectName("btnCalcTrainLabel")
        self.btnClear = QtWidgets.QPushButton(self.splitter)
        self.btnClear.setObjectName("btnClear")
        self.chBoxDrawPredict = QtWidgets.QCheckBox(Dialog)
        self.chBoxDrawPredict.setGeometry(QtCore.QRect(180, 780, 81, 16))
        self.chBoxDrawPredict.setObjectName("chBoxDrawPredict")
        self.btnPatch = QtWidgets.QPushButton(Dialog)
        self.btnPatch.setGeometry(QtCore.QRect(270, 670, 75, 23))
        self.btnPatch.setObjectName("btnPatch")
        self.comboClassNo = QtWidgets.QComboBox(Dialog)
        self.comboClassNo.setGeometry(QtCore.QRect(300, 750, 31, 21))
        self.comboClassNo.setMaxCount(2)
        self.comboClassNo.setObjectName("comboClassNo")
        self.comboClassNo.addItem("")
        self.comboClassNo.addItem("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(340, 750, 47, 21))
        self.label.setObjectName("label")
        self.splitter.raise_()
        self.view.raise_()
        self.viewLarge.raise_()
        self.view1.raise_()
        self.btnSave.raise_()
        self.leTrainFileName.raise_()
        self.sboxTrainFileName.raise_()
        self.btnLoad.raise_()
        self.view2.raise_()
        self.btnBatchGenerateLabel.raise_()
        self.label_2.raise_()
        self.edPath.raise_()
        self.btnTraining.raise_()
        self.btnMergeData.raise_()
        self.chBoxDrawPredict.raise_()
        self.btnPatch.raise_()
        self.comboClassNo.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog)
        self.btnLine.clicked.connect(Dialog.doLine)
        self.btnClear.clicked.connect(Dialog.clearWorld)
        self.btnSave.clicked.connect(Dialog.doSaveData)
        self.btnLoad.clicked.connect(Dialog.doLoadData)
        self.btnCalcTrainLabel.clicked.connect(Dialog.calcTrainLabel)
        self.btnCircle.clicked.connect(Dialog.doCircle)
        self.btnRandDraw.clicked.connect(Dialog.doRandDraw)
        self.btnBatchGenerateLabel.clicked.connect(Dialog.doBatchGenerateLabel)
        self.btnTraining.clicked.connect(Dialog.doTraining)
        self.btnMergeData.clicked.connect(Dialog.doMergeData)
        self.btnPatch.clicked.connect(Dialog.doPatch)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.btnClear, self.btnLine)
        Dialog.setTabOrder(self.btnLine, self.view)
        Dialog.setTabOrder(self.view, self.viewLarge)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.btnSave.setText(_translate("Dialog", "Save"))
        self.leTrainFileName.setText(_translate("Dialog", "AA/AA"))
        self.btnLoad.setText(_translate("Dialog", "Load"))
        self.btnBatchGenerateLabel.setText(_translate("Dialog", "BatchGenerateLabel"))
        self.label_2.setText(_translate("Dialog", "on Directory"))
        self.edPath.setText(_translate("Dialog", "All"))
        self.btnTraining.setText(_translate("Dialog", "Training"))
        self.btnMergeData.setText(_translate("Dialog", "MergeData"))
        self.btnCircle.setText(_translate("Dialog", "DrawCircle"))
        self.btnLine.setText(_translate("Dialog", "DrawLine"))
        self.btnRandDraw.setText(_translate("Dialog", "RandDraw"))
        self.btnCalcTrainLabel.setText(_translate("Dialog", "CalcLabel"))
        self.btnClear.setText(_translate("Dialog", "Clear"))
        self.chBoxDrawPredict.setText(_translate("Dialog", "DrawPredict"))
        self.btnPatch.setText(_translate("Dialog", "Patch"))
        self.comboClassNo.setItemText(0, _translate("Dialog", "2"))
        self.comboClassNo.setItemText(1, _translate("Dialog", "5"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>Classes</p></body></html>"))


